name = "breeze-breakers-api"
main = "api/src/index.ts"
compatibility_date = "2024-05-30"

# This setting tells wrangler dev to serve your 'public' folder
pages_build_output_dir = "public"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "breeze-breakers-db"
database_id = "bf8553d6-ec2a-4fab-9e97-448eb120fdf1"